#!/usr/bin/env python3
"""
Clean warranty_demo and warranty-ui for a fresh node migration.

Removes generated/migrated content so new migrations do not conflict with old ones.

USAGE:
  python3 clean_migration_targets.py
  python3 clean_migration_targets.py --dry-run
  python3 clean_migration_targets.py --warranty-demo-only
  python3 clean_migration_targets.py --warranty-ui-only

What gets removed:
  warranty_demo:
    - src/main/java/com/scania/warranty/{domain,repository,service,dto,web,config}/*.java
    - Keeps: WarrantyApplication.java
    - src/main/resources/static/angular/ (built UI output)
    - src/main/resources/ui-schemas/*.json (generated schemas)
    - target/ (Maven build output)
    - data/ (H2 database files)

  warranty-ui:
    - dist/ (Angular build output)
    - node_modules/ (optional, use --include-node-modules to remove)
"""

import argparse
import shutil
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent
WARRANTY_DEMO = ROOT / "warranty_demo"
WARRANTY_UI = ROOT / "warranty-ui"


def clean_warranty_demo(dry_run: bool = False) -> list[str]:
    """Remove generated Java, built UI, ui-schemas, target, and data from warranty_demo."""
    removed: list[str] = []
    java_root = WARRANTY_DEMO / "src" / "main" / "java" / "com" / "scania" / "warranty"

    # Packages to remove (generated by migration)
    packages = ["domain", "repository", "service", "dto", "web", "config"]
    for pkg in packages:
        pkg_dir = java_root / pkg
        if pkg_dir.is_dir():
            for f in pkg_dir.rglob("*.java"):
                rel = str(f.relative_to(WARRANTY_DEMO))
                if dry_run:
                    removed.append(f"[DRY-RUN] would remove {rel}")
                else:
                    f.unlink()
                    removed.append(f"removed {rel}")
            # Remove empty dirs
            if not dry_run and pkg_dir.exists():
                for d in sorted(pkg_dir.rglob("*"), key=lambda x: len(x.parts), reverse=True):
                    if d.is_dir() and not any(d.iterdir()):
                        d.rmdir()
                if not any(pkg_dir.iterdir()):
                    pkg_dir.rmdir()

    # Built Angular UI
    static_angular = WARRANTY_DEMO / "src" / "main" / "resources" / "static" / "angular"
    if static_angular.is_dir():
        if dry_run:
            removed.append(f"[DRY-RUN] would remove {static_angular.relative_to(WARRANTY_DEMO)}/")
        else:
            shutil.rmtree(static_angular)
            removed.append(f"removed {static_angular.relative_to(WARRANTY_DEMO)}/")

    # Generated ui-schemas
    ui_schemas = WARRANTY_DEMO / "src" / "main" / "resources" / "ui-schemas"
    if ui_schemas.is_dir():
        for f in ui_schemas.glob("*.json"):
            rel = str(f.relative_to(WARRANTY_DEMO))
            if dry_run:
                removed.append(f"[DRY-RUN] would remove {rel}")
            else:
                f.unlink()
                removed.append(f"removed {rel}")

    # Maven target
    target = WARRANTY_DEMO / "target"
    if target.is_dir():
        if dry_run:
            removed.append(f"[DRY-RUN] would remove {target.relative_to(WARRANTY_DEMO)}/")
        else:
            shutil.rmtree(target)
            removed.append(f"removed {target.relative_to(WARRANTY_DEMO)}/")

    # H2 data
    data = WARRANTY_DEMO / "data"
    if data.is_dir():
        if dry_run:
            removed.append(f"[DRY-RUN] would remove {data.relative_to(WARRANTY_DEMO)}/")
        else:
            shutil.rmtree(data)
            removed.append(f"removed {data.relative_to(WARRANTY_DEMO)}/")

    return removed


def clean_warranty_ui(dry_run: bool = False, include_node_modules: bool = False) -> list[str]:
    """Remove dist and optionally node_modules from warranty-ui."""
    removed: list[str] = []

    dist = WARRANTY_UI / "dist"
    if dist.is_dir():
        if dry_run:
            removed.append(f"[DRY-RUN] would remove {dist.relative_to(ROOT)}/")
        else:
            shutil.rmtree(dist)
            removed.append(f"removed {dist.relative_to(ROOT)}/")

    if include_node_modules:
        nm = WARRANTY_UI / "node_modules"
        if nm.is_dir():
            if dry_run:
                removed.append(f"[DRY-RUN] would remove {nm.relative_to(ROOT)}/")
            else:
                shutil.rmtree(nm)
                removed.append(f"removed {nm.relative_to(ROOT)}/")

    return removed


def main() -> None:
    parser = argparse.ArgumentParser(description="Clean warranty_demo and warranty-ui for fresh migration")
    parser.add_argument("--dry-run", action="store_true", help="Show what would be removed without deleting")
    parser.add_argument("--warranty-demo-only", action="store_true", help="Clean only warranty_demo")
    parser.add_argument("--warranty-ui-only", action="store_true", help="Clean only warranty-ui")
    parser.add_argument("--include-node-modules", action="store_true", help="Also remove warranty-ui/node_modules")
    args = parser.parse_args()

    all_removed: list[str] = []

    if not args.warranty_ui_only:
        if not WARRANTY_DEMO.is_dir():
            print(f"warranty_demo not found at {WARRANTY_DEMO}", file=sys.stderr)
        else:
            all_removed.extend(clean_warranty_demo(args.dry_run))

    if not args.warranty_demo_only:
        if not WARRANTY_UI.is_dir():
            print(f"warranty-ui not found at {WARRANTY_UI}", file=sys.stderr)
        else:
            all_removed.extend(clean_warranty_ui(args.dry_run, args.include_node_modules))

    for r in all_removed:
        print(r)
    print(f"\n{'Would remove' if args.dry_run else 'Removed'} {len(all_removed)} item(s).")


if __name__ == "__main__":
    main()
