#!/usr/bin/env python3
"""
Post-migration IdClass fixer for JPA entities with composite keys.

Scans domain entities for multiple @Id fields without @IdClass, then:
1. Creates XxxId.java with matching fields (Serializable, equals, hashCode)
2. Adds @IdClass(XxxId.class) to the entity
3. Updates XxxRepository to JpaRepository<Xxx, XxxId> if it uses a wrong ID type

USAGE:
  python3 fix_idclass.py <project_dir>

Called automatically after migration (migrate_to_pure_java.py) and before build.
"""

import re
import sys
from pathlib import Path
from typing import List, Optional, Tuple


def _extract_package(content: str) -> Optional[str]:
    m = re.search(r"package\s+([\w.]+)\s*;", content)
    return m.group(1) if m else None


def _extract_entity_class(content: str) -> Optional[str]:
    m = re.search(r"@Entity[\s\S]*?public\s+(?:class|interface)\s+(\w+)", content)
    return m.group(1) if m else None


def _has_idclass(content: str) -> bool:
    return "@IdClass(" in content


def _extract_id_fields(content: str) -> List[Tuple[str, str]]:
    """Extract (fieldName, fieldType) for each @Id field. Field name from 'private Type fieldName'."""
    fields = []
    # Match @Id followed by @Column (optional) and private Type fieldName;
    pattern = r"@Id\s*(?:@Column\([^)]*\)\s*)?private\s+(\w+(?:<[^>]+>)?)\s+(\w+)\s*;"
    for m in re.finditer(pattern, content):
        field_type = m.group(1)
        field_name = m.group(2)
        fields.append((field_name, field_type))
    return fields


def _generate_id_class(
    entity_name: str,
    package: str,
    id_fields: List[Tuple[str, str]],
) -> str:
    """Generate XxxId.java content."""
    class_name = f"{entity_name}Id"
    fields_decl = "\n    ".join(
        f"private {ft} {fn};" for fn, ft in id_fields
    )
    constructor_params = ", ".join(f"{ft} {fn}" for fn, ft in id_fields)
    constructor_assign = "\n        ".join(f"this.{fn} = {fn};" for fn, _ in id_fields)
    getters_setters = []
    for fn, ft in id_fields:
        cap = fn[0].upper() + fn[1:]
        getters_setters.append(f"""
    public {ft} get{cap}() {{ return {fn}; }}
    public void set{cap}({ft} {fn}) {{ this.{fn} = {fn}; }}""")
    getters_setters_str = "".join(getters_setters)
    equals_parts = " && ".join(f"Objects.equals({fn}, that.{fn})" for fn, _ in id_fields)
    hash_parts = ", ".join(fn for fn, _ in id_fields)
    return f'''package {package};

import java.io.Serializable;
import java.util.Objects;

/**
 * Composite primary key for {{@link {entity_name}}}.
 * Field names must match the @Id property names in {entity_name}.
 * Generated by fix_idclass.py (resilient pipeline).
 */
public class {class_name} implements Serializable {{

    {fields_decl}

    public {class_name}() {{
    }}

    public {class_name}({constructor_params}) {{
        {constructor_assign}
    }}
{getters_setters_str}

    @Override
    public boolean equals(Object o) {{
        if (this == o) return true;
        if (o == null || getClass() != o.getClass()) return false;
        {class_name} that = ({class_name}) o;
        return {equals_parts};
    }}

    @Override
    public int hashCode() {{
        return Objects.hash({hash_parts});
    }}
}}
'''


def _add_idclass_to_entity(content: str, id_class_name: str) -> str:
    """Add @IdClass(XxxId.class) after @Entity, before @Table or class."""
    if "@IdClass(" in content:
        return content
    insert = f"@IdClass({id_class_name}.class)\n"
    content = re.sub(r"(@Entity)\s*\n", r"\1\n" + insert, content, count=1)
    return content


def _find_repository_for_entity(project_dir: Path, entity_name: str) -> Optional[Path]:
    """Find repository interface for entity (e.g. ClaimRepository for Claim)."""
    repo_dir = project_dir / "src" / "main" / "java"
    repo_name = f"{entity_name}Repository.java"
    for path in repo_dir.rglob(repo_name):
        return path
    return None


def _update_repository_id_type(content: str, entity_name: str, id_class_name: str) -> str:
    """Change JpaRepository<Entity, String> to JpaRepository<Entity, IdClass>."""
    wrong_pattern = re.compile(
        r"JpaRepository\s*<\s*" + re.escape(entity_name) + r"\s*,\s*String\s*>"
    )
    if wrong_pattern.search(content):
        content = wrong_pattern.sub(
            f"JpaRepository<{entity_name}, {id_class_name}>",
            content,
        )
    return content


def _add_repository_import(content: str, package: str, id_class_name: str) -> str:
    """Add import for IdClass if not present."""
    import_line = f"import {package}.{id_class_name};"
    if import_line in content:
        return content
    # Add after last import
    import_pattern = re.compile(r"(import\s+[\w.]+;\s*\n)+")
    m = import_pattern.search(content)
    if m:
        end = m.end()
        content = content[:end] + import_line + "\n" + content[end:]
    return content


def fix_entity(project_dir: Path, entity_path: Path) -> List[Path]:
    """
    Fix one entity file if it has multiple @Id without @IdClass.
    Returns list of files created/modified.
    """
    changed = []
    content = entity_path.read_text(encoding="utf-8", errors="ignore")
    package = _extract_package(content)
    entity_name = _extract_entity_class(content)
    if not package or not entity_name:
        return changed

    id_fields = _extract_id_fields(content)
    if len(id_fields) < 2:
        return changed
    if _has_idclass(content):
        return changed

    id_class_name = f"{entity_name}Id"
    pkg_path = entity_path.parent
    id_file = pkg_path / f"{id_class_name}.java"

    # Create Id class only if it doesn't exist (avoid overwriting correct ones)
    if not id_file.exists():
        id_content = _generate_id_class(entity_name, package, id_fields)
        id_file.write_text(id_content, encoding="utf-8")
        changed.append(id_file)

    # Update entity
    new_content = _add_idclass_to_entity(content, id_class_name)
    entity_path.write_text(new_content, encoding="utf-8")
    changed.append(entity_path)

    # Update repository
    repo_path = _find_repository_for_entity(project_dir, entity_name)
    if repo_path:
        repo_content = repo_path.read_text(encoding="utf-8", errors="ignore")
        repo_content = _add_repository_import(repo_content, package, id_class_name)
        repo_content = _update_repository_id_type(repo_content, entity_name, id_class_name)
        repo_path.write_text(repo_content, encoding="utf-8")
        changed.append(repo_path)

    return changed


def run_fix(project_dir: Path) -> Tuple[int, List[str]]:
    """
    Scan all domain entities and fix IdClass issues.
    Returns (count_fixed, list of messages).
    """
    project_dir = Path(project_dir).resolve()
    java_root = project_dir / "src" / "main" / "java"
    if not java_root.is_dir():
        return 0, ["No src/main/java found"]

    domain_dir = None
    for d in java_root.rglob("domain"):
        if d.is_dir() and "main" in str(d):
            domain_dir = d
            break
    if not domain_dir or not domain_dir.is_dir():
        return 0, ["No domain package found"]

    messages = []
    total_fixed = 0
    for entity_path in domain_dir.glob("*.java"):
        if entity_path.name.endswith("Id.java") or entity_path.name.endswith("Key.java"):
            continue
        try:
            changed = fix_entity(project_dir, entity_path)
            if changed:
                total_fixed += 1
                for p in changed:
                    rel = p.relative_to(project_dir)
                    messages.append(f"Fixed: {rel}")
        except Exception as e:
            messages.append(f"Error processing {entity_path.name}: {e}")

    return total_fixed, messages


def main() -> None:
    if len(sys.argv) < 2:
        print("Usage: python3 fix_idclass.py <project_dir>", file=sys.stderr)
        sys.exit(1)
    project_dir = Path(sys.argv[1])
    if not project_dir.is_dir():
        print(f"Project directory not found: {project_dir}", file=sys.stderr)
        sys.exit(1)
    count, messages = run_fix(project_dir)
    for m in messages:
        print(m)
    if count > 0:
        print(f"\nIdClass fixer: {count} entity(ies) fixed.", file=sys.stderr)
    sys.exit(0)


if __name__ == "__main__":
    main()
