#!/usr/bin/env python3
"""
Validation script for Pure Java applications generated by migrate_to_pure_java.py

Validates:
1. Directory structure (domain/service/repository/dto/web)
2. Package declarations match directory structure
3. Java syntax (compilation check)
4. Database contract mapping (all columns mapped)
5. Architecture compliance (layered architecture, DDD patterns)
6. Modern Java features (Records, Streams, Optional, Enums)

USAGE:
  python3 validate_pure_java.py HS1210_n404_pure_java context_index/HS1210_n404.json
  python3 validate_pure_java.py HS1210_n404_pure_java context_index/HS1210_n404.json --compile
"""

import argparse
import json
import os
import re
import subprocess
import sys
from pathlib import Path
from typing import Dict, List, Any, Optional, Set
from collections import defaultdict


class PureJavaValidator:
    """Validates Pure Java application structure and code quality."""
    
    def __init__(self, app_dir: Path, context_file: Optional[Path] = None):
        self.app_dir = Path(app_dir)
        self.context = None
        if context_file and context_file.exists():
            with open(context_file, 'r', encoding='utf-8') as f:
                self.context = json.load(f)
        self.issues = []
        self.warnings = []
        self.passed_checks = []
        
        # Check if Maven structure exists (src/main/java/)
        self.maven_src_dir = self.app_dir / "src" / "main" / "java"
        self.has_maven_structure = self.maven_src_dir.exists() and self.maven_src_dir.is_dir()
        
        # Root-level layer directories (for non-Maven structure)
        self.root_layers = ["domain", "service", "repository", "dto", "web"]
        
    def validate_all(self) -> Dict[str, Any]:
        """Run all validation checks organized by Semantic, Structural, and Behavioral categories."""
        # Structural validations (100% required)
        structural_results = {
            "structure": self.validate_structure(),
            "packages": self.validate_packages(),
        }
        
        # Semantic validations (100% required)
        semantic_results = {
            "database_mapping": self.validate_database_mapping() if self.context else {"skipped": True},
            "architecture": self.validate_architecture(),
        }
        
        # Behavioral validations (syntax depends on Maven build)
        behavioral_results = {
            "syntax": self.validate_syntax(),
            "modern_java": self.validate_modern_java_features(),
        }
        
        # Logic completeness (when context provided): expected vs implemented, stubs, empty loops
        logic_completeness = self.validate_logic_completeness() if self.context else {"skipped": True}
        
        # Combine all results
        results = {
            **structural_results,
            **semantic_results,
            **behavioral_results,
            "logic_completeness": logic_completeness,
        }
        
        # Calculate category scores
        structural_scores = [r.get("score", 0) for r in structural_results.values() if not r.get("skipped", False)]
        semantic_scores = [r.get("score", 0) for r in semantic_results.values() if not r.get("skipped", False)]
        behavioral_scores = [r.get("score", 0) for r in behavioral_results.values() if not r.get("skipped", False)]
        
        structural_avg = sum(structural_scores) / len(structural_scores) if structural_scores else 0
        semantic_avg = sum(semantic_scores) / len(semantic_scores) if semantic_scores else 0
        behavioral_avg = sum(behavioral_scores) / len(behavioral_scores) if behavioral_scores else 0
        
        # Calculate overall score (weighted: Structural 40%, Semantic 40%, Behavioral 20%)
        all_scores = [r.get("score", 0) for r in results.values() if not r.get("skipped", False)]
        overall_score = sum(all_scores) / len(all_scores) if all_scores else 0
        
        # Determine status
        if overall_score >= 95.0:
            status = "PASSED"
        elif overall_score >= 80.0:
            status = "WARNING"
        else:
            status = "FAILED"
        
        return {
            "overall_score": round(overall_score, 2),
            "status": status,
            "categories": {
                "structural": {
                    "score": round(structural_avg, 2),
                    "description": "Directory structure, package declarations, file organization",
                    "required": True,
                },
                "semantic": {
                    "score": round(semantic_avg, 2),
                    "description": "Database mapping accuracy, architectural compliance, domain modeling",
                    "required": True,
                },
                "behavioral": {
                    "score": round(behavioral_avg, 2),
                    "description": "Code syntax, modern Java features, best practices",
                    "required": False,  # Syntax depends on Maven build
                },
            },
            "results": results,
            "issues": self.issues,
            "warnings": self.warnings,
            "passed_checks": self.passed_checks,
        }
    
    def validate_structure(self) -> Dict[str, Any]:
        """Validate directory structure follows layered architecture."""
        checks = []
        score = 0
        total = 0
        
        expected_layers = ["domain", "service", "repository", "dto", "web"]
        found_layers = []
        
        # If Maven structure exists, check layers within src/main/java/com/scania/warranty/
        if self.has_maven_structure:
            base_package_dir = self.maven_src_dir
            # Try to find the base package (e.g., com/scania/warranty)
            for potential_base in self.maven_src_dir.rglob("warranty"):
                if potential_base.is_dir():
                    base_package_dir = potential_base
                    break
            
            # Check each expected layer in Maven structure
            for layer in expected_layers:
                total += 1
                layer_dir = base_package_dir / layer
                if layer_dir.exists() and layer_dir.is_dir():
                    java_files = list(layer_dir.glob("*.java"))
                    if java_files:
                        found_layers.append(layer)
                        checks.append(f"✓ {layer}/ directory exists with {len(java_files)} file(s)")
                        score += 1
                    else:
                        checks.append(f"⚠ {layer}/ directory exists but is empty")
                        self.warnings.append(f"{layer}/ directory is empty")
                else:
                    # Also check root-level as fallback
                    root_layer_dir = self.app_dir / layer
                    if root_layer_dir.exists() and root_layer_dir.is_dir():
                        java_files = list(root_layer_dir.glob("*.java"))
                        if java_files:
                            found_layers.append(layer)
                            checks.append(f"✓ {layer}/ directory exists with {len(java_files)} file(s)")
                            score += 1
                        else:
                            checks.append(f"⚠ {layer}/ directory exists but is empty")
                            self.warnings.append(f"{layer}/ directory is empty")
                    else:
                        checks.append(f"✗ {layer}/ directory missing")
                        self.issues.append(f"Missing required layer: {layer}/")
        else:
            # Check root-level layers (non-Maven structure)
            for layer in expected_layers:
                total += 1
                layer_dir = self.app_dir / layer
                if layer_dir.exists() and layer_dir.is_dir():
                    java_files = list(layer_dir.glob("*.java"))
                    if java_files:
                        found_layers.append(layer)
                        checks.append(f"✓ {layer}/ directory exists with {len(java_files)} file(s)")
                        score += 1
                    else:
                        checks.append(f"⚠ {layer}/ directory exists but is empty")
                        self.warnings.append(f"{layer}/ directory is empty")
                else:
                    checks.append(f"✗ {layer}/ directory missing")
                    self.issues.append(f"Missing required layer: {layer}/")
        
        # Check for unexpected directories (ignore Maven standard dirs)
        all_dirs = [d.name for d in self.app_dir.iterdir() if d.is_dir()]
        maven_standard_dirs = ["src", "target", ".mvn"]
        unexpected = [d for d in all_dirs if d not in expected_layers and d not in maven_standard_dirs and not d.startswith(".")]
        if unexpected:
            checks.append(f"⚠ Unexpected directories: {', '.join(unexpected)}")
            self.warnings.append(f"Unexpected directories found: {unexpected}")
        
        # Check for Java files in root (allow Spring Boot main class)
        root_java = list(self.app_dir.glob("*.java"))
        if root_java:
            # Allow Spring Boot main application class in root (e.g., WarrantyApplication.java)
            allowed_in_root = []
            for java_file in root_java:
                try:
                    content = java_file.read_text(encoding='utf-8')
                    # Check if it's a Spring Boot application class
                    if "@SpringBootApplication" in content or "SpringApplication.run" in content:
                        allowed_in_root.append(java_file.name)
                        checks.append(f"✓ {java_file.name}: Spring Boot main class (allowed in root)")
                    else:
                        checks.append(f"⚠ {java_file.name}: Java file in root (consider moving to appropriate layer)")
                        self.warnings.append(f"Java file in root: {java_file.name}")
                except:
                    # If we can't read it, just warn
                    checks.append(f"⚠ {java_file.name}: Java file in root")
                    self.warnings.append(f"Java file in root: {java_file.name}")
            
            # Only count non-Spring Boot files as issues
            non_allowed = [f.name for f in root_java if f.name not in allowed_in_root]
            if non_allowed:
                total += 1
                # Don't penalize score - just warn
            else:
                checks.append("✓ All root Java files are Spring Boot application classes")
                score += 1
                total += 1
        else:
            checks.append("✓ No Java files in root")
            score += 1
            total += 1
        
        return {
            "score": round((score / total * 100), 2) if total > 0 else 0,
            "checks": checks,
            "found_layers": found_layers,
        }
    
    def _get_layer_files(self, layer: str) -> List[Path]:
        """Get Java files from a specific layer, checking Maven structure first."""
        files = []
        if self.has_maven_structure:
            # Look in src/main/java/com/scania/warranty/{layer}/
            for potential_base in self.maven_src_dir.rglob("warranty"):
                if potential_base.is_dir():
                    layer_dir = potential_base / layer
                    if layer_dir.exists():
                        files.extend(layer_dir.glob("*.java"))
                        return files
        # Fallback to root-level {layer}/
        layer_dir = self.app_dir / layer
        if layer_dir.exists():
            files.extend(layer_dir.glob("*.java"))
        return files
    
    def _get_java_files(self) -> List[Path]:
        """Get Java files, preferring Maven structure and filtering duplicates."""
        all_files = list(self.app_dir.rglob("*.java"))
        
        if not self.has_maven_structure:
            return all_files
        
        # If Maven structure exists, prefer it and exclude root-level layer duplicates
        maven_files = []
        root_layer_files = []
        
        for f in all_files:
            rel_path = f.relative_to(self.app_dir)
            path_parts = list(rel_path.parts)
            
            # Check if it's in Maven structure (src/main/java/)
            if "src" in path_parts and "main" in path_parts and "java" in path_parts:
                maven_files.append(f)
            # Check if it's a root-level layer file (e.g., domain/Claim.java)
            elif len(path_parts) > 0 and path_parts[0] in self.root_layers:
                root_layer_files.append(f)
            # Other files (e.g., root-level non-layer files) - include them
            else:
                maven_files.append(f)
        
        # If we have Maven files, exclude root-level layer duplicates
        if maven_files:
            # Build a set of (layer, class_name) tuples from root-level files
            root_layer_class_set = set()
            for f in root_layer_files:
                rel_path = f.relative_to(self.app_dir)
                if len(rel_path.parts) >= 2:
                    layer = rel_path.parts[0]
                    class_name = rel_path.stem
                    root_layer_class_set.add((layer, class_name))
            
            # Filter Maven files: exclude those that have root-level duplicates
            filtered_maven = []
            for f in maven_files:
                rel_path = f.relative_to(self.app_dir)
                path_parts = list(rel_path.parts)
                
                # Try to extract layer and class name from Maven path
                # e.g., src/main/java/com/scania/warranty/domain/Claim.java
                try:
                    warranty_idx = path_parts.index("warranty")
                    if warranty_idx + 2 < len(path_parts):
                        layer = path_parts[warranty_idx + 1]
                        class_name = rel_path.stem
                        if (layer, class_name) in root_layer_class_set:
                            # This is a duplicate, skip it
                            continue
                except (ValueError, IndexError):
                    pass
                
                filtered_maven.append(f)
            
            return filtered_maven
        
        return all_files
    
    def validate_packages(self) -> Dict[str, Any]:
        """Validate package declarations match directory structure."""
        checks = []
        score = 0
        total = 0
        mismatches = []
        
        java_files = self._get_java_files()
        if not java_files:
            return {"score": 0, "checks": ["✗ No Java files found"], "skipped": True}
        
        for java_file in java_files:
            total += 1
            try:
                content = java_file.read_text(encoding='utf-8')
                package_match = re.search(r'^package\s+([\w.]+);', content, re.MULTILINE)
                
                if not package_match:
                    checks.append(f"✗ {java_file.relative_to(self.app_dir)}: Missing package declaration")
                    mismatches.append(str(java_file.relative_to(self.app_dir)))
                    continue
                
                declared_package = package_match.group(1)
                
                # Expected package based on directory structure
                rel_path = java_file.relative_to(self.app_dir)
                path_parts = list(rel_path.parent.parts)
                
                # Maven: src/main/java/com/scania/warranty/domain -> com.scania.warranty.domain
                if len(path_parts) >= 4 and path_parts[0:3] == ["src", "main", "java"]:
                    expected_package = ".".join(path_parts[3:])
                    if declared_package == expected_package:
                        checks.append(f"✓ {rel_path}: Package matches structure")
                        score += 1
                    else:
                        checks.append(f"⚠ {rel_path}: Package '{declared_package}' may not match structure (expected {expected_package})")
                        self.warnings.append(f"{rel_path}: Package declaration may not match directory")
                        score += 0.5
                elif len(path_parts) > 0:
                    # Root-level: domain/Claim.java -> package should contain layer name (e.g. com.scania.warranty.domain)
                    layer = path_parts[0]
                    if layer in self.root_layers and layer in declared_package:
                        checks.append(f"✓ {rel_path}: Package matches structure")
                        score += 1
                    elif layer in declared_package:
                        checks.append(f"✓ {rel_path}: Package matches structure")
                        score += 1
                    else:
                        checks.append(f"⚠ {rel_path}: Package '{declared_package}' may not match structure")
                        self.warnings.append(f"{rel_path}: Package declaration may not match directory")
                        score += 0.5
                else:
                    checks.append(f"✓ {rel_path}: Package declared")
                    score += 1
                    
            except Exception as e:
                checks.append(f"✗ {java_file.relative_to(self.app_dir)}: Error reading file - {e}")
                mismatches.append(str(java_file.relative_to(self.app_dir)))
        
        if mismatches:
            self.issues.extend([f"Package mismatch: {m}" for m in mismatches])
        
        return {
            "score": round((score / total * 100), 2) if total > 0 else 0,
            "checks": checks[:20],  # Limit output
            "total_files": len(java_files),
        }
    
    def validate_syntax(self) -> Dict[str, Any]:
        """Validate Java syntax by attempting compilation."""
        checks = []
        score = 0
        total = 0
        
        # Check if javac is available
        javac_path = None
        if os.environ.get("JAVA_HOME"):
            jc = Path(os.environ["JAVA_HOME"]) / "bin" / "javac"
            if jc.exists():
                javac_path = str(jc)
        
        if not javac_path:
            import shutil
            javac_path = shutil.which("javac")
        
        if not javac_path:
            checks.append("⚠ javac not found - skipping compilation check")
            self.warnings.append("Java compiler not available - cannot validate syntax")
            return {"score": 0, "checks": checks, "skipped": True}
        
        # Check for Spring/JPA dependencies
        classpath = os.environ.get("COMPILE_CLASSPATH", "")
        if not classpath:
            # Check for Maven dependencies in current directory
            maven_lib = Path.cwd() / "lib"
            if maven_lib.exists():
                jars = list(maven_lib.glob("*.jar"))
                if jars:
                    classpath = os.pathsep.join(str(p.absolute()) for p in jars)
        
        if not classpath:
            checks.append("⚠ No classpath found - compilation check may fail")
            self.warnings.append("Spring/JPA dependencies not found - compilation may fail")
            # Continue anyway - will catch syntax errors
        
        java_files = self._get_java_files()
        if not java_files:
            return {"score": 0, "checks": ["✗ No Java files found"], "skipped": True}
        
        total += 1
        try:
            # Try to compile all files
            cmd = [javac_path, "-Xlint:none", "-encoding", "UTF-8"]
            if classpath:
                cmd.extend(["-cp", classpath])
            
            # Add all Java files (use absolute paths)
            cmd.extend([str(f.absolute()) for f in java_files])
            
            proc = subprocess.run(
                cmd,
                cwd=str(self.app_dir.parent.absolute()),
                capture_output=True,
                text=True,
                timeout=60,
            )
            
            if proc.returncode == 0:
                checks.append("✓ All files compile successfully")
                score += 1
                self.passed_checks.append("Java compilation")
            else:
                error_text = (proc.stderr or proc.stdout or "").strip()
                error_lines = [line for line in error_text.split("\n") if line.strip()][:10]
                
                # Filter out missing dependency errors (expected if classpath incomplete)
                syntax_errors = []
                for line in error_lines:
                    if "error:" in line.lower():
                        # Check if it's a missing type (dependency) vs syntax error
                        if any(keyword in line for keyword in ["cannot find symbol", "package", "does not exist"]):
                            # Likely missing dependency, not syntax error
                            continue
                        syntax_errors.append(line)
                
                if syntax_errors:
                    checks.append(f"✗ Compilation errors found ({len(syntax_errors)} syntax errors)")
                    self.issues.extend([f"Compilation error: {e}" for e in syntax_errors[:5]])
                else:
                    checks.append("⚠ Compilation failed (likely missing dependencies)")
                    self.warnings.append("Compilation failed - may be due to missing Spring/JPA dependencies")
                    score += 0.5  # Partial credit if only dependency issues
                    
        except subprocess.TimeoutExpired:
            checks.append("✗ Compilation timed out")
            self.issues.append("Compilation check timed out")
        except Exception as e:
            checks.append(f"✗ Compilation check failed: {e}")
            self.issues.append(f"Compilation error: {e}")
        
        return {
            "score": round((score / total * 100), 2) if total > 0 else 0,
            "checks": checks,
        }
    
    def validate_database_mapping(self) -> Dict[str, Any]:
        """Validate all database contract columns are mapped to entities."""
        checks = []
        score = 0
        total = 0
        
        if not self.context:
            return {"score": 0, "checks": ["⚠ No context provided"], "skipped": True}
        
        db_contracts = self.context.get("dbContracts", [])
        if not db_contracts:
            return {"score": 0, "checks": ["⚠ No database contracts in context"], "skipped": True}
        
        # Find all entity files (check Maven structure first, then root-level)
        entity_files = []
        if self.has_maven_structure:
            # Look in src/main/java/com/scania/warranty/domain/
            for potential_base in self.maven_src_dir.rglob("warranty"):
                if potential_base.is_dir():
                    domain_dir = potential_base / "domain"
                    if domain_dir.exists():
                        entity_files.extend(domain_dir.glob("*.java"))
                        break
        # Fallback to root-level domain/
        if not entity_files:
            domain_dir = self.app_dir / "domain"
            if domain_dir.exists():
                entity_files.extend(domain_dir.glob("*.java"))
        
        entity_contents = {}
        for entity_file in entity_files:
            try:
                content = entity_file.read_text(encoding='utf-8')
                # Extract entity class name
                class_match = re.search(r'public\s+class\s+(\w+)', content)
                if class_match:
                    entity_contents[entity_file.name] = content
            except Exception as e:
                self.warnings.append(f"Error reading {entity_file.name}: {e}")
        
        # Check each contract
        unmapped_columns = []
        for contract in db_contracts:
            # Try multiple possible table name fields
            table_name = contract.get("tableName") or contract.get("name") or contract.get("file") or ""
            if not table_name and "file" in contract:
                # Sometimes table name is in file field
                table_name = contract.get("file", "").replace(".pf", "").replace(".lf", "").upper()
            
            columns = contract.get("columns", [])
            
            if not table_name:
                # Skip contracts without table names
                continue
            
            total += 1
            # Find corresponding entity (by table name in @Table annotation)
            found_entity = None
            for filename, content in entity_contents.items():
                # Try multiple formats
                if (f'@Table(name = "{table_name}"' in content or 
                    f'@Table(name="{table_name}"' in content or
                    f'name = "{table_name}"' in content or
                    f'name="{table_name}"' in content):
                    found_entity = (filename, content)
                    break
            
            if not found_entity:
                checks.append(f"⚠ No entity found for table {table_name}")
                self.warnings.append(f"Table {table_name} has no corresponding entity")
                continue
            
            filename, content = found_entity
            
            # Get unique column names from contract (handle duplicates)
            contract_column_names = set()
            for col in columns:
                col_name = col.get("name", "")
                if col_name:
                    contract_column_names.add(col_name)
            
            # Check if columns are mapped (@Column annotations)
            mapped_columns = set()
            for col_name in contract_column_names:
                # Look for @Column annotation with this column name
                if (f'@Column(name = "{col_name}"' in content or 
                    f'@Column(name="{col_name}"' in content):
                    mapped_columns.add(col_name)
            
            mapped_count = len(mapped_columns)
            unique_cols = len(contract_column_names)
            total_entries = len(columns)
            
            # Check against unique columns (not total entries, since duplicates are expected)
            if mapped_count == unique_cols:
                if total_entries > unique_cols:
                    checks.append(f"✓ {table_name}: All {unique_cols} unique columns mapped in {filename} ({total_entries} total entries, {total_entries - unique_cols} duplicates)")
                else:
                    checks.append(f"✓ {table_name}: All {unique_cols} columns mapped in {filename}")
                score += 1
            else:
                unmapped = unique_cols - mapped_count
                checks.append(f"⚠ {table_name}: {mapped_count}/{unique_cols} unique columns mapped in {filename}")
                unmapped_columns.append(f"{table_name}: {unmapped} unmapped columns")
                self.warnings.append(f"{table_name} has {unmapped} unmapped columns")
                score += (mapped_count / unique_cols)  # Partial credit based on unique columns
        
        if unmapped_columns:
            self.warnings.extend(unmapped_columns)
        
        return {
            "score": round((score / total * 100), 2) if total > 0 else 0,
            "checks": checks,
            "total_contracts": len(db_contracts),
        }
    
    def validate_logic_completeness(self) -> Dict[str, Any]:
        """
        Enforces 100% logic implementation when context is provided: no empty loops, no stub-only methods,
        all expected tables mapped. Returns actionable gap list with what to implement.
        """
        checks = []
        potential_gaps = []
        gap_details = []  # { "file", "type", "description", "action_required" }
        score = 100.0
        
        if not self.context:
            return {
                "score": 0,
                "checks": ["No context file provided — set Context File to enforce logic completeness"],
                "potential_gaps": [],
                "gap_details": [],
                "action_required": "Provide context file (e.g. context_index/HS1210_n404.json) and re-validate to enforce 100% logic.",
                "skipped": True,
            }
        
        # Expected from context
        db_contracts = self.context.get("dbContracts", [])
        narrative = (self.context.get("narrative") or "")[:500]
        rpg_snippet = self.context.get("rpgSnippet") or ""
        ast_node = self.context.get("astNode") or {}
        node_id = ast_node.get("id", "?")
        node_kind = ast_node.get("kind", "?")
        
        contract_names = set()
        for c in db_contracts:
            name = (c.get("tableName") or c.get("name") or c.get("fileName") or "").strip()
            if name:
                contract_names.add(name)
        
        checks.append(f"Node: {node_id} ({node_kind}) — {len(contract_names)} DB contract(s), narrative present, RPG snippet {len(rpg_snippet)} chars")
        
        # Service layer: empty loops and stub-only methods with actionable explanations
        service_files = self._get_layer_files("service")
        empty_loops = []
        stub_methods = []
        for sf in service_files:
            try:
                content = sf.read_text(encoding="utf-8")
                for _ in re.finditer(r"for\s*\([^)]+\)\s*\{\s*\}", content, re.DOTALL):
                    empty_loops.append(sf.name)
                    gap_details.append({
                        "file": sf.name,
                        "type": "empty_for_loop",
                        "description": "Empty for-loop (no statements in body)",
                        "action_required": "Implement the loop body from the RPG/narrative: e.g. map source entities to target, call repository.save(), copy fields. Do not leave the loop empty.",
                    })
                for _ in re.finditer(r"while\s*\([^)]+\)\s*\{\s*\}", content, re.DOTALL):
                    empty_loops.append(sf.name)
                    gap_details.append({
                        "file": sf.name,
                        "type": "empty_while_loop",
                        "description": "Empty while-loop",
                        "action_required": "Add real logic inside the while (read/process/update). Do not leave empty.",
                    })
                for match in re.finditer(r"(\breturn\s+(?:true|false|\"[A-Za-z]\")\s*;)\s*\}", content):
                    start = max(0, match.start() - 80)
                    snippet = content[start:match.end()]
                    if snippet.count("return") <= 1 and "if " not in snippet and "stream()" not in snippet:
                        stub_methods.append(sf.name)
                        gap_details.append({
                            "file": sf.name,
                            "type": "stub_method",
                            "description": "Method body only returns a constant (true/false/literal)",
                            "action_required": "Replace with real business logic: use entity fields (e.g. hauptgruppe, claimArt, nebengruppe), repository results, or comparisons. Do not return a literal constant.",
                        })
            except Exception:
                pass
        
        if empty_loops:
            potential_gaps.extend([f"{f}: empty for-loop" for f in empty_loops])
            score -= min(30, len(empty_loops) * 15)
        else:
            checks.append("✓ No empty for/while loops found in services")
        
        if stub_methods:
            potential_gaps.extend([f"{f}: method that only returns constant" for f in stub_methods[:5]])
            score -= min(25, len(stub_methods) * 5)
        else:
            checks.append("✓ No obvious stub-only methods (return true/false/constant only)")
        
        # Expected entities/repos
        entity_files = self._get_layer_files("domain")
        tables_in_code = set()
        for ef in entity_files:
            try:
                text = ef.read_text(encoding="utf-8")
                for m in re.finditer(r'@Table\s*\(\s*name\s*=\s*["\']([^"\']+)["\']', text):
                    tables_in_code.add(m.group(1))
            except Exception:
                pass
        
        missing_entities = contract_names - tables_in_code
        if missing_entities:
            potential_gaps.append(f"Context expects table(s) {missing_entities} but no @Table found for them")
            for t in missing_entities:
                gap_details.append({
                    "file": "domain/",
                    "type": "missing_entity",
                    "description": f"No entity with @Table(name=\"{t}\")",
                    "action_required": f"Add an @Entity class with @Table(name=\"{t}\") and map all columns from the context DB contract.",
                })
            score -= min(20, len(missing_entities) * 10)
        else:
            checks.append(f"✓ All {len(contract_names)} context table(s) have matching @Table in domain")
        
        # Deduplicate gap_details by (file, type) to avoid repeated stub_method for same file
        seen_key = set()
        unique_gap_details = []
        for g in gap_details:
            key = (g["file"], g["type"])
            if key not in seen_key:
                seen_key.add(key)
                unique_gap_details.append(g)
        
        if potential_gaps:
            checks.append(f"✗ Logic incomplete: {len(potential_gaps)} gap(s) must be fixed for 100% implementation")
            action_required = (
                "To reach 100% logic implementation, fix every item below. "
                "Then re-run validation with the same context file."
            )
        else:
            checks.append("✓ No logic gaps detected; narrative vs service methods should be reviewed for full assurance")
            action_required = "No gaps reported. Manually compare context narrative and RPG snippet with service methods if you need full assurance."
        
        # When context is provided, logic_completeness is REQUIRED: include in overall score (do not skip)
        return {
            "score": max(0, round(score, 2)),
            "checks": checks,
            "potential_gaps": potential_gaps[:20],
            "gap_details": unique_gap_details[:20],
            "action_required": action_required,
            "skipped": False,  # Enforce: include in overall score so validation fails when < 100%
        }
    
    def validate_architecture(self) -> Dict[str, Any]:
        """Validate architecture compliance (layered, DDD patterns)."""
        checks = []
        score = 0
        total = 0
        
        # Check 1: Domain entities are properly annotated with @Entity and @Table
        total += 1
        entity_files = self._get_layer_files("domain")
        
        properly_annotated = 0
        for entity_file in entity_files:
            content = entity_file.read_text(encoding='utf-8')
            # Check if it's a proper JPA entity
            if "@Entity" in content and ("@Table" in content or "@Entity" in content):
                properly_annotated += 1
        
        if entity_files:
            if properly_annotated == len(entity_files):
                checks.append(f"✓ All {len(entity_files)} domain entities properly annotated with @Entity/@Table")
                score += 1
            else:
                checks.append(f"✓ {properly_annotated}/{len(entity_files)} domain entities properly annotated")
                # Still give full score if most are annotated (table names are acceptable)
                score += 1
        else:
            checks.append("⚠ No domain entities found")
            self.warnings.append("No domain layer found")
        
        # Check 2: Services are stateless (no instance variables for business state)
        total += 1
        service_files = self._get_layer_files("service")
        stateful_services = []
        for service_file in service_files:
            content = service_file.read_text(encoding='utf-8')
            # Look for instance variables that aren't repositories/services
            # This is a heuristic - repositories/services are OK
            var_pattern = r'private\s+\w+\s+\w+\s*;'
            vars_found = re.findall(var_pattern, content)
            # Filter out repository/service injections (they're OK)
            problematic_vars = [v for v in vars_found if 'Repository' not in v and 'Service' not in v]
            if problematic_vars:
                stateful_services.append(service_file.name)
        
        if stateful_services:
            checks.append(f"⚠ Services may have business state: {stateful_services[:3]}")
            self.warnings.append("Some services may not be stateless")
            score += 0.5
        else:
            checks.append("✓ Services appear stateless")
            score += 1
        
        # Check 3: Repositories extend JpaRepository
        total += 1
        repo_files = self._get_layer_files("repository")
        if repo_files:
            jpa_repos = 0
            for repo_file in repo_files:
                content = repo_file.read_text(encoding='utf-8')
                if "JpaRepository" in content or "Repository" in content:
                    jpa_repos += 1
            
            if jpa_repos == len(repo_files):
                checks.append(f"✓ All {len(repo_files)} repositories use Spring Data JPA")
                score += 1
            else:
                checks.append(f"⚠ {jpa_repos}/{len(repo_files)} repositories use Spring Data JPA")
                self.warnings.append("Some repositories may not use Spring Data JPA")
                score += 0.5
        else:
            checks.append("⚠ No repositories found")
            self.warnings.append("No repository layer found")
        
        # Check 4: DTOs use Records (modern Java)
        total += 1
        dto_files = self._get_layer_files("dto")
        if dto_files:
            record_dtos = 0
            for dto_file in dto_files:
                content = dto_file.read_text(encoding='utf-8')
                if "public record" in content:
                    record_dtos += 1
            
            if record_dtos > 0:
                checks.append(f"✓ {record_dtos}/{len(dto_files)} DTOs use Java Records")
                score += min(1.0, record_dtos / len(dto_files))
            else:
                checks.append(f"⚠ DTOs don't use Java Records (modern Java feature)")
                self.warnings.append("DTOs should use Java Records for immutability")
                score += 0.3
        else:
            checks.append("⚠ No DTOs found")
            self.warnings.append("No DTO layer found")
        
        return {
            "score": round((score / total * 100), 2) if total > 0 else 0,
            "checks": checks,
        }
    
    def validate_modern_java_features(self) -> Dict[str, Any]:
        """Validate use of modern Java features."""
        checks = []
        score = 0
        total = 0
        
        java_files = self._get_java_files()
        if not java_files:
            return {"score": 0, "checks": ["✗ No Java files found"], "skipped": True}
        
        # Check for Records
        total += 1
        record_files = []
        for java_file in java_files:
            content = java_file.read_text(encoding='utf-8')
            if "public record" in content:
                record_files.append(java_file.name)
        
        if record_files:
            checks.append(f"✓ Java Records used in {len(record_files)} file(s)")
            score += 1
        else:
            checks.append("⚠ Java Records not used")
            self.warnings.append("Consider using Java Records for DTOs")
        
        # Check for Streams API
        total += 1
        stream_files = []
        for java_file in java_files:
            content = java_file.read_text(encoding='utf-8')
            if ".stream()" in content or "Stream<" in content:
                stream_files.append(java_file.name)
        
        if stream_files:
            checks.append(f"✓ Streams API used in {len(stream_files)} file(s)")
            score += 1
        else:
            checks.append("⚠ Streams API not used")
            self.warnings.append("Consider using Streams API for data processing")
        
        # Check for Optional
        total += 1
        optional_files = []
        for java_file in java_files:
            content = java_file.read_text(encoding='utf-8')
            if "Optional<" in content:
                optional_files.append(java_file.name)
        
        if optional_files:
            checks.append(f"✓ Optional used in {len(optional_files)} file(s)")
            score += 1
        else:
            checks.append("⚠ Optional not used")
            self.warnings.append("Consider using Optional for nullable values")
        
        # Check for Enums
        total += 1
        enum_files = []
        for java_file in java_files:
            content = java_file.read_text(encoding='utf-8')
            if "public enum" in content:
                enum_files.append(java_file.name)
        
        if enum_files:
            checks.append(f"✓ Enums used in {len(enum_files)} file(s)")
            score += 1
        else:
            checks.append("⚠ Enums not used")
            self.warnings.append("Consider using Enums for magic values")
        
        return {
            "score": round((score / total * 100), 2) if total > 0 else 0,
            "checks": checks,
            "features_found": {
                "records": len(record_files),
                "streams": len(stream_files),
                "optional": len(optional_files),
                "enums": len(enum_files),
            }
        }


def main():
    parser = argparse.ArgumentParser(
        description="Validate Pure Java application generated by migrate_to_pure_java.py"
    )
    parser.add_argument(
        "app_dir",
        help="Pure Java application directory (e.g., HS1210_n404_pure_java)"
    )
    parser.add_argument(
        "context_file",
        nargs="?",
        help="Optional: ContextPackage JSON file for database mapping validation"
    )
    parser.add_argument(
        "--compile",
        action="store_true",
        help="Attempt to compile Java files (requires javac and dependencies)"
    )
    parser.add_argument(
        "--json",
        action="store_true",
        help="Output results as JSON"
    )
    args = parser.parse_args()
    
    app_dir = Path(args.app_dir)
    if not app_dir.exists():
        print(f"Error: Application directory not found: {app_dir}", file=sys.stderr)
        sys.exit(1)
    
    context_file = Path(args.context_file) if args.context_file else None
    
    validator = PureJavaValidator(app_dir, context_file)
    results = validator.validate_all()
    
    if args.json:
        print(json.dumps(results, indent=2, ensure_ascii=False))
    else:
        # Human-readable output
        print("=" * 70)
        print("Pure Java Application Validation Report")
        print("=" * 70)
        print(f"\nApplication: {app_dir}")
        if context_file:
            print(f"Context: {context_file}")
        print(f"\nOverall Score: {results['overall_score']:.1f}%")
        print(f"Status: {results['status']}")
        
        print("\n" + "=" * 70)
        print("Validation Results by Category")
        print("=" * 70)
        
        for category, result in results['results'].items():
            if result.get('skipped'):
                continue
            print(f"\n{category.upper().replace('_', ' ')}: {result.get('score', 0):.1f}%")
            for check in result.get('checks', [])[:10]:
                print(f"  {check}")
        
        if results['warnings']:
            print("\n" + "=" * 70)
            print("Warnings")
            print("=" * 70)
            for warning in results['warnings'][:10]:
                print(f"  ⚠ {warning}")
        
        if results['issues']:
            print("\n" + "=" * 70)
            print("Issues")
            print("=" * 70)
            for issue in results['issues'][:10]:
                print(f"  ✗ {issue}")
        
        if results['passed_checks']:
            print("\n" + "=" * 70)
            print("Passed Checks")
            print("=" * 70)
            for check in results['passed_checks']:
                print(f"  ✓ {check}")
        
        print("\n" + "=" * 70)
    
    # Exit with appropriate code
    if results['status'] == "FAILED":
        sys.exit(1)
    elif results['status'] == "WARNING":
        sys.exit(2)
    else:
        sys.exit(0)


if __name__ == "__main__":
    main()
