package com.scania.warranty.dto;

import com.scania.warranty.domain.ClaimError;
import com.scania.warranty.domain.ClaimStatus;
import com.scania.warranty.domain.ClaimType;

public record ClaimErrorDto(
    Long id,
    String claimNumber,
    String errorNumber,
    String reconNumber,
    String damagingPart,
    String mainGroup,
    String damageCode,
    String subGroup,
    String description1,
    String description2,
    String description3,
    String description4,
    String controlCode,
    Integer materialPercentage,
    Integer labourPercentage,
    Integer specialPercentage,
    String claimType,
    String claimTypeDescription,
    Integer previousRepairDate,
    Integer previousMileage,
    Integer previousRepairNumber,
    String campaignNumber,
    String epsName,
    Integer status,
    String statusDescription,
    String alternateErrorNumber,
    String codeC1,
    String codeC2,
    String codeC3,
    String codeC4,
    String codeC5,
    String codeC6,
    String resultCode,
    String resultType,
    String resultId,
    String faultType,
    String faultId,
    String repairType,
    String repairId,
    String explanationType,
    String explanationId
) {
    public static ClaimErrorDto fromEntity(ClaimError error) {
        return new ClaimErrorDto(
            error.getId(),
            error.getClaimNumber(),
            error.getErrorNumber(),
            error.getReconNumber(),
            error.getDamagingPart(),
            error.getMainGroup(),
            error.getDamageCode(),
            error.getSubGroup(),
            error.getDescription1(),
            error.getDescription2(),
            error.getDescription3(),
            error.getDescription4(),
            error.getControlCode(),
            error.getMaterialPercentage(),
            error.getLabourPercentage(),
            error.getSpecialPercentage(),
            error.getClaimType(),
            ClaimType.fromCode(error.getClaimType()).getDescription(),
            error.getPreviousRepairDate(),
            error.getPreviousMileage(),
            error.getPreviousRepairNumber(),
            error.getCampaignNumber(),
            error.getEpsName(),
            error.getStatus(),
            ClaimStatus.fromCode(error.getStatus()).getDescription(),
            error.getAlternateErrorNumber(),
            error.getCodeC1(),
            error.getCodeC2(),
            error.getCodeC3(),
            error.getCodeC4(),
            error.getCodeC5(),
            error.getCodeC6(),
            error.getResultCode(),
            error.getResultType(),
            error.getResultId(),
            error.getFaultType(),
            error.getFaultId(),
            error.getRepairType(),
            error.getRepairId(),
            error.getExplanationType(),
            error.getExplanationId()
        );
    }
}